- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install package(s)
  ansible.builtin.apt:
    name: nginx-full
    state: present

- name: Template HTTP config
  template:
    src: http_vhost.conf.j2
    dest: /etc/nginx/conf.d/http_vhost.conf
  notify: Restart NGINX

- name: Template TCP/UDP config
  template:
    src: stream_tcp_udp.conf.j2
    dest: /etc/nginx/conf.d/stream_tcp_udp.conf
  notify: Restart NGINX

- name: Ensure NGINX is running
  service:
    name: nginx
    state: started
    enabled: true
